package constellation;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/** 
 Generate, and save to a file, a sequence of PostScript drawing commands for drawing a constellation.
 
 <P>Lines and dots are drawn, but no labels or special symbols.
 
 <P>To get a pleasing output in PostScript, the user will need to manually adjust the 
 geometry (origin, scale, and rotation) before running commands generated by this class. 
*/
public final class BuildConstellationDrawing {
  
  public static void main(String... args) throws IOException {
    //BuildConstellationDrawing constellation = new BuildConstellationDrawing("Tau", new Projection(4, 30, 16), new File("constellaton-data-8859-1/taurus.ps"));
    //BuildConstellationDrawing constellation = new BuildConstellationDrawing("Peg", new Projection(23, 0, 20), new File("constellaton-data-8859-1/pegasus.ps"));
    //BuildConstellationDrawing constellation = new BuildConstellationDrawing("Sco", new Projection(16, 40, -30), new File("constellaton-data-8859-1/scorpius.ps"));
    //BuildConstellationDrawing constellation = new BuildConstellationDrawing("Cas", new Projection(1, 0, 60), new File("constellaton-data-8859-1/cass.ps"));
    BuildConstellationDrawing constellation = new BuildConstellationDrawing("Ori", new Projection(5, 38, 3), new File("constellaton-data-8859-1/orion.ps"));
    constellation.build();
  }

  /**
   Ctor. 
   @param constellationAbbr 'Ori', for example.
   @param proj an equirectangular projection, centered near the target, used to generate XY coords for PostScript.
  */
  public BuildConstellationDrawing(String constellationAbbr, Projection proj, File outputFile) {
    this.constellationAbbr = constellationAbbr;
    this.outputFile = outputFile;
    this.projection = proj;
  }

  /** Generate the file containing PostScript code. */
  public void build() throws IOException {
    StarCatalog starCatalog = new StarCatalog();
    ConstellationLines constellationLinesCatalog = new ConstellationLines();
    polylines = constellationLinesCatalog.polylinesFor(constellationAbbr);
    for(List<Integer> polyline : polylines) {
      for (Integer id : polyline) {
        Star star = starCatalog.lookup(id);
        projection.calcXY(star); //changes the state of the star object
        lineStars.put(id, star);
      }
    }
    outputStarLines();
  }
  
  private String constellationAbbr;
  private Projection projection;
  private File outputFile;
  
  private List<List<Integer>> polylines = new ArrayList<>();
  private Map<Integer, Star> lineStars = new LinkedHashMap<>();
  
  //private List<UnattachedStarTarget> unattachedStarTargets;
  //private List<Star> unattachedStars;
  
  private static final String sp = " ";
  
  private void outputStarLines() throws IOException {
    FileOutputStream fos = new FileOutputStream(outputFile);
    BufferedWriter writer = new BufferedWriter(new OutputStreamWriter(fos, DataFileReader.ENCODING));
    for(List<Integer> polyline : polylines) {
      writer.write("[");
      for(Integer id : polyline) {
        Star star = lineStars.get(id);
        writer.write("[" + star.X + sp + star.Y + "] ");
      }
      writer.write("] draw-star-line"); //PostScript command for drawing a polyline
      writer.newLine();
    }
    for(Integer id : lineStars.keySet()) {
      Star star = lineStars.get(id);
      writer.write(drawStarPS(star));
      writer.newLine();
    }
    writer.close();    
  }
  
  /** PostScript command for drawing a star. */
  private String drawStarPS(Star star) {
    return star.X + sp + star.Y + sp + star.MAG + " draw-star-point";
  }
}
